language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
install:
  - python bootstrap-buildout.py
  - bin/buildout -N
script:
  - make -k test
after_success:
  - easy_install coveralls
  - coveralls
